# Generated by Django 5.1.15 on 2026-06-04 11:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acervo', '0013_mapear_areas_legadas'),
        ('vocabulario', '0003_padroniza_grafia_bases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Revisão de escopo — Análise Cognitiva', max_length=300)),
                ('pergunta_pesquisa', models.TextField(blank=True)),
                ('criterios_inclusao', models.TextField(blank=True, help_text='Critérios de inclusão pré-registrados (PRISMA-ScR).')),
                ('criterios_exclusao', models.TextField(blank=True, help_text='Critérios de exclusão pré-registrados (PRISMA-ScR).')),
                ('n_revisores', models.PositiveSmallIntegerField(default=2, help_text='Revisores independentes por registro (≥2).')),
                ('prazo_dias', models.PositiveSmallIntegerField(default=21, help_text='Prazo (dias) para concluir cada triagem.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'protocolo de triagem',
                'verbose_name_plural': 'protocolos de triagem',
            },
        ),
        migrations.CreateModel(
            name='Busca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outra_base', models.CharField(blank=True, help_text='Base fora do vocabulário controlado.', max_length=200)),
                ('string_busca', models.TextField(blank=True, help_text='String de busca usada (para reprodutibilidade).')),
                ('data_busca', models.DateField(blank=True, null=True)),
                ('n_identificados', models.PositiveIntegerField(default=0, help_text='Total de registros relatado pela base (para o PRISMA).')),
                ('arquivo', models.FileField(blank=True, help_text='Export cru (RIS/BibTeX/CSV), guardado para auditoria.', null=True, upload_to='triagem/buscas/')),
                ('formato', models.CharField(blank=True, choices=[('ris', 'RIS'), ('bibtex', 'BibTeX'), ('csv', 'CSV')], max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('base_consulta', models.ForeignKey(blank=True, help_text='Base bibliográfica (reusa o vocabulário `base`).', limit_choices_to={'vocabulario__codigo': 'base'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buscas_triagem', to='vocabulario.termovocabulario')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buscas_triagem', to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buscas', to='triagem.protocolotriagem')),
            ],
            options={
                'verbose_name': 'busca',
                'verbose_name_plural': 'buscas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('autores', models.TextField(blank=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=17)),
                ('resumo', models.TextField(blank=True)),
                ('palavras_chaves', models.TextField(blank=True)),
                ('titulo_periodico', models.TextField(blank=True)),
                ('idioma', models.CharField(blank=True, max_length=20)),
                ('link', models.URLField(blank=True, max_length=600)),
                ('identificador', models.CharField(db_index=True, help_text='Chave determinística de dedup (DOI>ISBN>hash).', max_length=80)),
                ('status', models.CharField(choices=[('identificado', 'Identificado'), ('em_triagem', 'Em triagem'), ('incluido', 'Incluído'), ('excluido', 'Excluído'), ('duplicado', 'Duplicado')], db_index=True, default='identificado', max_length=15)),
                ('motivo_exclusao', models.TextField(blank=True, help_text='Motivo da exclusão (PRISMA: excluded with reasons).')),
                ('ja_no_acervo', models.BooleanField(db_index=True, default=False, help_text='Casa com Artigo já existente (inclusive legado): não re-triar.')),
                ('decisao_final', models.CharField(blank=True, choices=[('incluir', 'Incluir'), ('excluir', 'Excluir'), ('duvida', 'Em dúvida')], help_text='Decisão consolidada (consenso ou desempate).', max_length=10)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(blank=True, help_text='Artigo correspondente: por promoção (incluído) ou por casar com o acervo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_triagem', to='acervo.artigo')),
                ('decidida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triagens_decididas', to=settings.AUTH_USER_MODEL)),
                ('duplicado_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicatas', to='triagem.registrotriagem')),
                ('origem_buscas', models.ManyToManyField(blank=True, help_text='Buscas em que este registro apareceu (uma ou mais bases).', related_name='registros', to='triagem.busca')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='triagem.protocolotriagem')),
            ],
            options={
                'verbose_name': 'registro de triagem',
                'verbose_name_plural': 'registros de triagem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistroTriagem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('autores', models.TextField(blank=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=17)),
                ('resumo', models.TextField(blank=True)),
                ('palavras_chaves', models.TextField(blank=True)),
                ('titulo_periodico', models.TextField(blank=True)),
                ('idioma', models.CharField(blank=True, max_length=20)),
                ('link', models.URLField(blank=True, max_length=600)),
                ('identificador', models.CharField(db_index=True, help_text='Chave determinística de dedup (DOI>ISBN>hash).', max_length=80)),
                ('status', models.CharField(choices=[('identificado', 'Identificado'), ('em_triagem', 'Em triagem'), ('incluido', 'Incluído'), ('excluido', 'Excluído'), ('duplicado', 'Duplicado')], db_index=True, default='identificado', max_length=15)),
                ('motivo_exclusao', models.TextField(blank=True, help_text='Motivo da exclusão (PRISMA: excluded with reasons).')),
                ('ja_no_acervo', models.BooleanField(db_index=True, default=False, help_text='Casa com Artigo já existente (inclusive legado): não re-triar.')),
                ('decisao_final', models.CharField(blank=True, choices=[('incluir', 'Incluir'), ('excluir', 'Excluir'), ('duvida', 'Em dúvida')], help_text='Decisão consolidada (consenso ou desempate).', max_length=10)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('artigo', models.ForeignKey(blank=True, db_constraint=False, help_text='Artigo correspondente: por promoção (incluído) ou por casar com o acervo.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acervo.artigo')),
                ('decidida_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='triagem.protocolotriagem')),
                ('duplicado_de', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='triagem.registrotriagem')),
            ],
            options={
                'verbose_name': 'historical registro de triagem',
                'verbose_name_plural': 'historical registros de triagem',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DecisaoTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(blank=True, choices=[('incluir', 'Incluir'), ('excluir', 'Excluir'), ('duvida', 'Em dúvida')], max_length=10, null=True)),
                ('motivo_exclusao', models.TextField(blank=True)),
                ('comentario', models.TextField(blank=True)),
                ('sorteado_em', models.DateTimeField(auto_now_add=True)),
                ('prazo_em', models.DateTimeField()),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triagens_feitas', to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to='triagem.registrotriagem')),
            ],
            options={
                'verbose_name': 'decisão de triagem',
                'verbose_name_plural': 'decisões de triagem',
                'ordering': ['-sorteado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='registrotriagem',
            constraint=models.UniqueConstraint(fields=('protocolo', 'identificador'), name='uniq_registro_por_identificador_protocolo'),
        ),
        migrations.AddConstraint(
            model_name='decisaotriagem',
            constraint=models.UniqueConstraint(fields=('registro', 'revisor'), name='uniq_decisao_por_revisor_registro'),
        ),
    ]
