# Generated by Django 5.1.15 on 2026-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_seed_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='busca',
            name='importado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busca',
            name='n_duplicados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busca',
            name='n_ignorados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busca',
            name='n_ja_no_acervo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busca',
            name='n_lidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='busca',
            name='n_novos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
