# Generated by Django 5.1.15 on 2026-06-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0004_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParDuplicataDescartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registro_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='triagem.registrotriagem')),
                ('registro_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='triagem.registrotriagem')),
            ],
            options={
                'verbose_name': 'par descartado (não duplicata)',
                'verbose_name_plural': 'pares descartados (não duplicatas)',
                'constraints': [models.UniqueConstraint(fields=('registro_a', 'registro_b'), name='uniq_par_descartado')],
            },
        ),
    ]
