# Generated by Django 5.1.15 on 2026-06-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0005_parduplicatadescartado'),
    ]

    operations = [
        migrations.AddField(
            model_name='busca',
            name='filtros',
            field=models.TextField(blank=True, help_text='Filtros/limites aplicados (anos, idioma, tipo de documento…).'),
        ),
    ]
