# Generated by Django 5.1.15 on 2026-06-04 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0006_busca_filtros'),
    ]

    operations = [
        migrations.AddField(
            model_name='busca',
            name='ano_fim',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busca',
            name='ano_inicio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busca',
            name='campo_busca',
            field=models.CharField(blank=True, choices=[('topico', 'Tópico'), ('titulo', 'Título'), ('resumo', 'Resumo'), ('palavras_chave', 'Palavras-chave'), ('todos', 'Todos os campos')], help_text='Em que campo a query foi aplicada.', max_length=20),
        ),
        migrations.AddField(
            model_name='busca',
            name='idiomas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='Idiomas filtrados na base.', size=None),
        ),
        migrations.AddField(
            model_name='busca',
            name='tipos_documento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Tipos de documento filtrados na base.', size=None),
        ),
        migrations.AlterField(
            model_name='busca',
            name='filtros',
            field=models.TextField(blank=True, help_text='Outros filtros/limites não cobertos pelos campos acima.'),
        ),
    ]
