# Generated by Django 5.1.15 on 2026-06-04 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0007_busca_ano_fim_busca_ano_inicio_busca_campo_busca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busca',
            name='campo_busca',
        ),
        migrations.AddField(
            model_name='busca',
            name='campos_busca',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Em que campo(s) a query foi aplicada.', size=None),
        ),
    ]
