# Generated by Django 5.1.15 on 2026-06-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0008_remove_busca_campo_busca_busca_campos_busca'),
    ]

    operations = [
        migrations.AddField(
            model_name='busca',
            name='idioma_outro',
            field=models.CharField(blank=True, help_text="Especificação quando 'Outro' é escolhido em idiomas.", max_length=100),
        ),
    ]
