# Generated by Django 5.1.15 on 2026-06-04 17:44

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0013_mapear_areas_legadas'),
        ('triagem', '0009_busca_idioma_outro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registrotriagem',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('titulo'), name='gin_trgm_ops'), name='triagem_reg_titulo_trgm'),
        ),
    ]
