# Generated by Django 5.1.15 on 2026-06-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0010_registrotriagem_triagem_reg_titulo_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrotriagem',
            name='tipo',
            field=models.CharField(blank=True, help_text='Tipo de documento (Artigo, Livro…).', max_length=40),
        ),
        migrations.AddField(
            model_name='registrotriagem',
            name='tipo',
            field=models.CharField(blank=True, help_text='Tipo de documento (Artigo, Livro…).', max_length=40),
        ),
    ]
