# Generated by Django 5.1.15 on 2026-06-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0011_historicalregistrotriagem_tipo_registrotriagem_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolotriagem',
            name='termos_realce',
            field=models.TextField(blank=True, help_text='Termos destacados no título/resumo durante a triagem (separados por vírgula).'),
        ),
    ]
