# Generated by Django 5.1.15 on 2026-06-05 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0013_termos_realce_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolotriagem',
            name='registro_externo',
            field=models.URLField(blank=True, help_text='Registro público do protocolo (ex.: OSF) — a priori.', max_length=300),
        ),
        migrations.AddField(
            model_name='protocolotriagem',
            name='travado_em',
            field=models.DateTimeField(blank=True, help_text='Quando esta versão foi travada (a priori).', null=True),
        ),
        migrations.AddField(
            model_name='protocolotriagem',
            name='usa_texto_completo',
            field=models.BooleanField(default=False, help_text='Ativa a 2ª etapa de triagem (texto completo) após o título/resumo.'),
        ),
        migrations.AddField(
            model_name='protocolotriagem',
            name='versao',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SnapshotProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveSmallIntegerField()),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='triagem.protocolotriagem')),
                ('travado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'versão do protocolo',
                'verbose_name_plural': 'versões do protocolo',
                'ordering': ['-versao'],
                'constraints': [models.UniqueConstraint(fields=('protocolo', 'versao'), name='uniq_versao_por_protocolo')],
            },
        ),
    ]
