# Generated by Django 5.1.15 on 2026-06-05 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0014_protocolotriagem_registro_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='decisaotriagem',
            name='uniq_decisao_por_revisor_registro',
        ),
        migrations.AddField(
            model_name='decisaotriagem',
            name='etapa',
            field=models.CharField(choices=[('ta', 'Título e resumo'), ('tc', 'Texto completo')], db_index=True, default='ta', help_text='Etapa da triagem (título/resumo ou texto completo).', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalregistrotriagem',
            name='status',
            field=models.CharField(choices=[('identificado', 'Identificado'), ('em_triagem', 'Em triagem (título/resumo)'), ('incluido_ta', 'Incluído no título/resumo'), ('em_texto', 'Em triagem (texto completo)'), ('incluido', 'Incluído'), ('excluido', 'Excluído (título/resumo)'), ('excluido_tc', 'Excluído (texto completo)'), ('duplicado', 'Duplicado')], db_index=True, default='identificado', max_length=15),
        ),
        migrations.AlterField(
            model_name='registrotriagem',
            name='status',
            field=models.CharField(choices=[('identificado', 'Identificado'), ('em_triagem', 'Em triagem (título/resumo)'), ('incluido_ta', 'Incluído no título/resumo'), ('em_texto', 'Em triagem (texto completo)'), ('incluido', 'Incluído'), ('excluido', 'Excluído (título/resumo)'), ('excluido_tc', 'Excluído (texto completo)'), ('duplicado', 'Duplicado')], db_index=True, default='identificado', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='decisaotriagem',
            constraint=models.UniqueConstraint(fields=('registro', 'revisor', 'etapa'), name='uniq_decisao_por_revisor_registro_etapa'),
        ),
    ]
