# Generated by Django 5.1.15 on 2026-06-05 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0015_remove_decisaotriagem_uniq_decisao_por_revisor_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisaotriagem',
            name='etapa',
            field=models.CharField(choices=[('ta', 'Título e resumo'), ('tc', 'Texto completo'), ('ca', 'Calibração (piloto)')], db_index=True, default='ta', help_text='Etapa da triagem (título/resumo ou texto completo).', max_length=2),
        ),
        migrations.CreateModel(
            name='RodadaCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('n_itens', models.PositiveIntegerField(default=0)),
                ('n_revisores', models.PositiveIntegerField(default=0)),
                ('perc_acordo', models.FloatField(blank=True, null=True)),
                ('kappa', models.FloatField(blank=True, null=True)),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibracoes', to='triagem.protocolotriagem')),
                ('registros', models.ManyToManyField(help_text='Amostra comum triada por toda a equipe.', related_name='calibracoes', to='triagem.registrotriagem')),
            ],
            options={
                'verbose_name': 'rodada de calibração',
                'verbose_name_plural': 'rodadas de calibração',
                'ordering': ['-criada_em'],
            },
        ),
    ]
