# Generated by Django 5.1.15 on 2026-06-05 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0016_alter_decisaotriagem_etapa_rodadacalibracao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrotriagem',
            name='duplicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistrotriagem',
            name='duplicado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Quem resolveu este registro como duplicata (auditoria).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parduplicatadescartado',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pares_descartados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrotriagem',
            name='duplicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrotriagem',
            name='duplicado_por',
            field=models.ForeignKey(blank=True, help_text='Quem resolveu este registro como duplicata (auditoria).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicatas_resolvidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
