# Generated by Django 5.1.15 on 2026-06-05 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0017_historicalregistrotriagem_duplicado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolotriagem',
            name='arquivado',
            field=models.BooleanField(default=False, help_text='Projeto concluído: some dos seletores, sem ser apagado.'),
        ),
        migrations.AddField(
            model_name='protocolotriagem',
            name='estrategia_busca',
            field=models.TextField(blank=True, help_text='String/lógica de busca que define a revisão (ex.: BLOCO 1 AND BLOCO 2).'),
        ),
        migrations.AddField(
            model_name='protocolotriagem',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome curto do projeto (para a interface).', max_length=120),
        ),
        migrations.AddField(
            model_name='protocolotriagem',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador do projeto na URL (/triagem/p/<slug>/).', max_length=140, unique=True),
        ),
        migrations.CreateModel(
            name='ProjetoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('analista', 'Analista'), ('curador', 'Curador')], default='analista', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='triagem.protocolotriagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_triagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membro do projeto',
                'verbose_name_plural': 'membros do projeto',
                'ordering': ['projeto', 'usuario'],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'usuario'), name='uniq_membro_por_projeto')],
            },
        ),
    ]
