# Generated by Django 5.1.15 on 2026-06-05 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0013_mapear_areas_legadas'),
        ('triagem', '0019_projeto_inicial_e_membros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrotriagem',
            name='relevancia_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Nº de termos da estratégia de busca presentes no título/resumo/palavras-chave. Cache de ordenação (Revisão ANCO); recalculável.'),
        ),
        migrations.AddField(
            model_name='protocolotriagem',
            name='modo',
            field=models.CharField(choices=[('rigoroso', 'Rigoroso (PRISMA-ScR)'), ('anco', 'Revisão ANCO (simplificado)')], default='rigoroso', help_text='Rigoroso: triagem por ≥2 revisores independentes (PRISMA-ScR). Revisão ANCO: o dono da base autotria; sorteio distribui cotas de análise. Apenas comuta o fluxo — o código rigoroso permanece.', max_length=10),
        ),
        migrations.AddField(
            model_name='registrotriagem',
            name='relevancia_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Nº de termos da estratégia de busca presentes no título/resumo/palavras-chave. Cache de ordenação (Revisão ANCO); recalculável.'),
        ),
        migrations.CreateModel(
            name='SorteioAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_revisao', models.CharField(choices=[('unica', 'Revisão única (1 analista)'), ('dupla', 'Revisão dupla (2 analistas + consenso)')], default='unica', help_text='Decidido pelo curador no momento do sorteio.', max_length=10)),
                ('cota', models.PositiveSmallIntegerField(default=5, help_text='Artigos atribuídos a cada analista.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, help_text='Critério/observações do sorteio (auditoria).')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorteios_analise_criados', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteios_analise', to='triagem.protocolotriagem')),
            ],
            options={
                'verbose_name': 'sorteio de análise',
                'verbose_name_plural': 'sorteios de análise',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConsensoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conciliado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analise_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consenso_final', to='acervo.analise')),
                ('analises', models.ManyToManyField(blank=True, help_text='As análises independentes que entraram na conciliação.', related_name='consensos_origem', to='acervo.analise')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensos', to='acervo.artigo')),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consensos_conciliados', to=settings.AUTH_USER_MODEL)),
                ('sorteio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consensos', to='triagem.sorteioanalise')),
            ],
            options={
                'verbose_name': 'consenso de análise',
                'verbose_name_plural': 'consensos de análise',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_analise', to=settings.AUTH_USER_MODEL)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_analise', to='acervo.artigo')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='triagem.sorteioanalise')),
            ],
            options={
                'verbose_name': 'atribuição de análise',
                'verbose_name_plural': 'atribuições de análise',
                'ordering': ['sorteio', 'analista', 'artigo'],
                'indexes': [models.Index(fields=['analista', 'artigo'], name='triagem_atr_analist_007fa3_idx')],
                'constraints': [models.UniqueConstraint(fields=('sorteio', 'analista', 'artigo'), name='uniq_atribuicao_por_sorteio_analista_artigo')],
            },
        ),
    ]
