# Generated by Django 5.1.15 on 2026-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0020_historicalregistrotriagem_relevancia_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteioanalise',
            name='semente',
            field=models.BigIntegerField(blank=True, help_text='Seed do embaralhamento aleatório (reprodutível/auditável).', null=True),
        ),
    ]
