# Generated by Django 5.1.15 on 2026-06-14 17:10
# Separação ANCO × PRISMA (Fase C, destrutiva): remove modo, relevancia_score e os
# models de sorteio/consenso (ANCO migrou para apps/anco). Antes de dropar o campo
# `modo`, arquiva os projetos que eram ANCO (somem da lista PRISMA; os links antigos
# já redirecionam para /anco/ via _anco_movido). Os dados ANCO já foram migrados.

from django.db import migrations


def _arquivar_anco(apps, schema_editor):
    Protocolo = apps.get_model("triagem", "ProtocoloTriagem")
    Protocolo.objects.filter(modo="anco").update(arquivado=True)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0021_sorteioanalise_semente'),
    ]

    operations = [
        migrations.RunPython(_arquivar_anco, _noop),
        migrations.RemoveField(
            model_name='consensoanalise',
            name='analise_final',
        ),
        migrations.RemoveField(
            model_name='consensoanalise',
            name='analises',
        ),
        migrations.RemoveField(
            model_name='consensoanalise',
            name='artigo',
        ),
        migrations.RemoveField(
            model_name='consensoanalise',
            name='conciliado_por',
        ),
        migrations.RemoveField(
            model_name='consensoanalise',
            name='sorteio',
        ),
        migrations.RemoveField(
            model_name='sorteioanalise',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='sorteioanalise',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='historicalregistrotriagem',
            name='relevancia_score',
        ),
        migrations.RemoveField(
            model_name='protocolotriagem',
            name='modo',
        ),
        migrations.RemoveField(
            model_name='registrotriagem',
            name='relevancia_score',
        ),
        migrations.DeleteModel(
            name='AtribuicaoAnalise',
        ),
        migrations.DeleteModel(
            name='ConsensoAnalise',
        ),
        migrations.DeleteModel(
            name='SorteioAnalise',
        ),
    ]
