# Generated by Django 5.1.15 on 2026-06-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0022_remove_consensoanalise_analise_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetomembro',
            name='revisor_independente',
            field=models.BooleanField(default=True, help_text='Participa da triagem como revisor independente (decide incluir/excluir). O curador define quantos revisores o projeto tem marcando isto na equipe.'),
        ),
    ]
