# Generated by Django 5.1.15 on 2026-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_interesse',
            field=models.TextField(blank=True, help_text='Áreas de interesse separadas por ponto-e-vírgula.'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio_curta',
            field=models.CharField(blank=True, help_text='Apresentação curta (até 280 caracteres).', max_length=280),
        ),
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo/posição (ex: Professor titular).', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de perfil. Se vazia, usa a foto do Google ou iniciais.', null=True, upload_to='usuarios/fotos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='lattes_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='linhas_pesquisa',
            field=models.TextField(blank=True, help_text='Linhas de pesquisa (texto livre).'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='orientador',
            field=models.CharField(blank=True, help_text='Orientador(a) — para mestrandos/doutorandos.', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='pagina_pessoal_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='programa_pos',
            field=models.CharField(blank=True, help_text='Programa de pós-graduação quando aplicável.', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='titulacao',
            field=models.CharField(blank=True, choices=[('graduando', 'Graduando'), ('graduado', 'Graduado'), ('mestrando', 'Mestrando'), ('mestre', 'Mestre'), ('doutorando', 'Doutorando'), ('doutor', 'Doutor'), ('pos_doc', 'Pós-doutorado'), ('professor', 'Professor')], db_index=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='unidade_departamento',
            field=models.CharField(blank=True, help_text='Unidade/departamento/programa (ex: DMMDC).', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='vinculo_institucional',
            field=models.CharField(blank=True, help_text='Instituição principal (ex: IFBA).', max_length=300),
        ),
    ]
