# Generated by Django 5.1.15 on 2026-05-28 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_campos_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocadastro',
            name='tipo',
            field=models.CharField(choices=[('analista', 'Analista'), ('revisor', 'Revisor')], db_index=True, default='analista', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='revisor_aprovado',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcado pela aprovação de uma SolicitacaoCadastro tipo=revisor.'),
        ),
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='solicitacaocadastro',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejeitada'), _negated=True), fields=('usuario', 'tipo'), name='uniq_solicitacao_ativa_por_tipo'),
        ),
    ]
