# Generated by Django 5.1.15 on 2026-05-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitacao_tipada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaocadastro',
            name='justificativa',
            field=models.TextField(blank=True),
        ),
    ]
