# Generated by Django 5.1.15 on 2026-06-14 17:45
# Fase D (separação ANCO × PRISMA): acesso por usuário a cada módulo. Backfill:
# quem já é membro de algum projeto ANCO recebe pode_anco=True (não perde acesso).

from django.db import migrations, models


def _backfill_anco(apps, schema_editor):
    User = apps.get_model("core", "User")
    MembroANCO = apps.get_model("anco", "MembroANCO")
    ids = MembroANCO.objects.values_list("usuario_id", flat=True).distinct()
    User.objects.filter(pk__in=list(ids)).update(pode_anco=True)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_justificativa_opcional'),
        ('anco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pode_anco',
            field=models.BooleanField(default=False, help_text='Acessa o módulo de Revisão ANCO (Análise Cognitiva).'),
        ),
        migrations.AddField(
            model_name='user',
            name='pode_prisma',
            field=models.BooleanField(default=True, help_text='Acessa o módulo de Revisão de escopo (PRISMA-ScR).'),
        ),
        migrations.RunPython(_backfill_anco, _noop),
    ]
