# Generated by Django 5.1.15 on 2026-09-04 12:32

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_pode_anco_user_pode_prisma'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.core.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='eh_conta_servico',
            field=models.BooleanField(db_index=True, default=False, help_text='Conta administrativa ou de teste, nao pertencente a equipe de pesquisa. Fica fora do diretorio publico e das contagens.', verbose_name='conta de serviço'),
        ),
    ]
