# Generated by Django 5.1.15 on 2026-06-14 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acervo', '0015_artigo_area_outra_alter_artigo_area'),
        ('vocabulario', '0003_padroniza_grafia_bases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoANCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('pergunta_pesquisa', models.TextField(blank=True, help_text='Objetivo da revisão.')),
                ('estrategia_busca', models.TextField(blank=True)),
                ('arquivado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'projeto ANCO',
                'verbose_name_plural': 'projetos ANCO',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FonteImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outra_base', models.CharField(blank=True, max_length=200)),
                ('string_busca', models.TextField(blank=True)),
                ('data_busca', models.DateField(blank=True, null=True)),
                ('formato', models.CharField(blank=True, choices=[('ris', 'RIS'), ('bibtex', 'BibTeX'), ('csv', 'CSV')], max_length=10)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='anco/fontes/')),
                ('n_lidos', models.PositiveIntegerField(default=0)),
                ('n_novos', models.PositiveIntegerField(default=0)),
                ('n_duplicados', models.PositiveIntegerField(default=0)),
                ('n_ignorados', models.PositiveIntegerField(default=0)),
                ('importado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('base_consulta', models.ForeignKey(blank=True, help_text='Base bibliográfica (reusa o vocabulário `base`).', limit_choices_to={'vocabulario__codigo': 'base'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes_anco', to='vocabulario.termovocabulario')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontes_anco', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='anco.projetoanco')),
            ],
            options={
                'verbose_name': 'fonte (import) ANCO',
                'verbose_name_plural': 'fontes (imports) ANCO',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SorteioANCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_revisao', models.CharField(choices=[('unica', 'Revisão única (1 analista)'), ('dupla', 'Revisão dupla (2 analistas + consenso)')], default='unica', max_length=10)),
                ('cota', models.PositiveSmallIntegerField(default=5)),
                ('semente', models.BigIntegerField(blank=True, help_text='Seed do embaralhamento (reprodutível/auditável).', null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorteios_anco', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteios', to='anco.projetoanco')),
            ],
            options={
                'verbose_name': 'sorteio de análise (ANCO)',
                'verbose_name_plural': 'sorteios de análise (ANCO)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConsensoANCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conciliado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analise_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consenso_anco_final', to='acervo.analise')),
                ('analises', models.ManyToManyField(blank=True, related_name='consensos_anco_origem', to='acervo.analise')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensos_anco', to='acervo.artigo')),
                ('conciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consensos_anco', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensos', to='anco.projetoanco')),
                ('sorteio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consensos', to='anco.sorteioanco')),
            ],
            options={
                'verbose_name': 'consenso de análise (ANCO)',
                'verbose_name_plural': 'consensos de análise (ANCO)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MembroANCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('analista', 'Analista'), ('curador', 'Curador')], default='analista', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos_anco', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='anco.projetoanco')),
            ],
            options={
                'verbose_name': 'membro do projeto ANCO',
                'verbose_name_plural': 'membros do projeto ANCO',
                'ordering': ['projeto', 'usuario'],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'usuario'), name='uniq_membro_anco')],
            },
        ),
        migrations.CreateModel(
            name='ItemCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('autores', models.TextField(blank=True)),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=40)),
                ('resumo', models.TextField(blank=True)),
                ('palavras_chaves', models.TextField(blank=True)),
                ('titulo_periodico', models.CharField(blank=True, max_length=300)),
                ('idioma', models.CharField(blank=True, max_length=20)),
                ('link', models.CharField(blank=True, max_length=600)),
                ('tipo', models.CharField(blank=True, max_length=40)),
                ('identificador', models.CharField(db_index=True, help_text='Chave de deduplicação interna.', max_length=64)),
                ('removido', models.BooleanField(default=False)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_remocao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(blank=True, help_text='Artigo no acervo (promovido/vinculado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_anco', to='acervo.artigo')),
                ('origem_fontes', models.ManyToManyField(blank=True, related_name='itens', to='anco.fonteimport')),
                ('removido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_anco_removidos', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='anco.projetoanco')),
            ],
            options={
                'verbose_name': 'item do corpus',
                'verbose_name_plural': 'itens do corpus',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'identificador'), name='uniq_item_anco_por_projeto')],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoANCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_anco', to=settings.AUTH_USER_MODEL)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_anco', to='acervo.artigo')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='anco.sorteioanco')),
            ],
            options={
                'verbose_name': 'atribuição de análise (ANCO)',
                'verbose_name_plural': 'atribuições de análise (ANCO)',
                'ordering': ['sorteio', 'analista', 'artigo'],
                'indexes': [models.Index(fields=['analista', 'artigo'], name='anco_atribu_analist_52cee3_idx')],
                'constraints': [models.UniqueConstraint(fields=('sorteio', 'analista', 'artigo'), name='uniq_atribuicao_anco')],
            },
        ),
    ]
