# Generated by Django 5.1.15 on 2026-07-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonteimport',
            name='individual',
            field=models.BooleanField(default=False),
        ),
    ]
