# Generated by Django 5.1.15 on 2026-04-29 14:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'vocabulário',
                'verbose_name_plural': 'vocabulários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TermoVocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('sinonimos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Termos inativos nao aparecem em formularios; usar para itens do legado pendentes de curadoria.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('vocabulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos', to='vocabulario.vocabulario')),
            ],
            options={
                'verbose_name': 'termo do vocabulário',
                'verbose_name_plural': 'termos do vocabulário',
                'ordering': ['vocabulario__nome', 'nome'],
                'constraints': [models.UniqueConstraint(fields=('vocabulario', 'nome'), name='uniq_termo_por_vocabulario')],
            },
        ),
    ]
