# Generated by Django 5.1.15 on 2026-07-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulario', '0003_padroniza_grafia_bases'),
    ]

    operations = [
        migrations.AddField(
            model_name='termovocabulario',
            name='grupo',
            field=models.CharField(blank=True, choices=[('paradigma', 'Paradigma / epistemologia'), ('metodologia', 'Abordagem metodológica'), ('disciplina', 'Campo / disciplina'), ('aplicacao', 'Domínio de aplicação'), ('lixo', 'Não-termo (descartar)')], db_index=True, default='', help_text='Faceta do termo (paradigma × metodologia × disciplina × aplicação). Organiza os pickers sem apagar nada; vazio = não classificado.', max_length=20),
        ),
    ]
