# Generated by Django 5.1.15 on 2026-04-29 14:43

import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida para revisão'), ('em_revisao', 'Em revisão'), ('aprovada', 'Aprovada'), ('publicada', 'Publicada no acervo'), ('legado', 'Legado pré-validado'), ('despublicada', 'Despublicada')], db_index=True, default='rascunho', max_length=20)),
                ('presenca_titulo', models.BooleanField(blank=True, null=True)),
                ('presenca_resumo', models.BooleanField(blank=True, null=True)),
                ('presenca_palavras_chave', models.BooleanField(blank=True, null=True)),
                ('presenca_referencias', models.BooleanField(blank=True, null=True)),
                ('presenca_corpo', models.BooleanField(blank=True, null=True)),
                ('pertinencia', models.BooleanField(blank=True, null=True)),
                ('aspectos_relevantes', models.TextField(blank=True)),
                ('define_conceito', models.BooleanField(blank=True, null=True)),
                ('definicao_extraida', models.TextField(blank=True)),
                ('objeto', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('foco', models.TextField(blank=True)),
                ('metodologia', models.TextField(blank=True)),
                ('referenciais', models.TextField(blank=True)),
                ('resultados', models.TextField(blank=True)),
                ('contexto_producao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('resenha_critica', models.TextField(blank=True, help_text='Texto critico autoral. Quando preenchido, dispara revisao cega adicional e ganha selo de destaque.')),
                ('tem_resenha', models.BooleanField(db_index=True, default=False, help_text='Cache para filtros — atualizado automaticamente no save().')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('submetida_em', models.DateTimeField(blank=True, null=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'análise',
                'verbose_name_plural': 'análises',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(db_index=True, help_text='DOI canonico ou identificador interno deterministico (legacy:HASH).', max_length=200, unique=True)),
                ('titulo', models.TextField()),
                ('titulo_periodico', models.TextField(blank=True)),
                ('ano', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2027)])),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('pagina_inicial', models.CharField(blank=True, max_length=20)),
                ('pagina_final', models.CharField(blank=True, max_length=20)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('autores', models.TextField(blank=True)),
                ('vinculacao_institucional', models.TextField(blank=True)),
                ('palavras_chaves', models.TextField(blank=True)),
                ('resumo', models.TextField(blank=True)),
                ('link_acesso', models.URLField(blank=True, help_text='Link primario para a obra. Pode ficar vazio em registros legado.', max_length=600)),
                ('link_acesso_alternativo', models.URLField(blank=True, help_text='Repositorio institucional, preprint, mirror.', max_length=600)),
                ('artigo_pago', models.BooleanField(default=False)),
                ('acesso_aberto', models.BooleanField(default=False, help_text='Selo: obra com licenca de acesso aberto.')),
                ('link_status', models.CharField(choices=[('nao_verificado', 'Não verificado'), ('ok', 'OK'), ('quebrado', 'Quebrado'), ('redireciona', 'Redireciona')], db_index=True, default='nao_verificado', max_length=20)),
                ('link_ultima_verificacao', models.DateTimeField(blank=True, null=True)),
                ('eh_legado', models.BooleanField(db_index=True, default=False, help_text='Marca artigos importados do JSON legado.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'artigo',
                'verbose_name_plural': 'artigos',
                'ordering': ['-ano', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(help_text="Nome do campo da Analise comentado (ex: 'metodologia', 'resenha_critica').", max_length=50)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'comentário de revisão',
                'verbose_name_plural': 'comentários de revisão',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAnalise',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida para revisão'), ('em_revisao', 'Em revisão'), ('aprovada', 'Aprovada'), ('publicada', 'Publicada no acervo'), ('legado', 'Legado pré-validado'), ('despublicada', 'Despublicada')], db_index=True, default='rascunho', max_length=20)),
                ('presenca_titulo', models.BooleanField(blank=True, null=True)),
                ('presenca_resumo', models.BooleanField(blank=True, null=True)),
                ('presenca_palavras_chave', models.BooleanField(blank=True, null=True)),
                ('presenca_referencias', models.BooleanField(blank=True, null=True)),
                ('presenca_corpo', models.BooleanField(blank=True, null=True)),
                ('pertinencia', models.BooleanField(blank=True, null=True)),
                ('aspectos_relevantes', models.TextField(blank=True)),
                ('define_conceito', models.BooleanField(blank=True, null=True)),
                ('definicao_extraida', models.TextField(blank=True)),
                ('objeto', models.TextField(blank=True)),
                ('objetivo', models.TextField(blank=True)),
                ('foco', models.TextField(blank=True)),
                ('metodologia', models.TextField(blank=True)),
                ('referenciais', models.TextField(blank=True)),
                ('resultados', models.TextField(blank=True)),
                ('contexto_producao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('resenha_critica', models.TextField(blank=True, help_text='Texto critico autoral. Quando preenchido, dispara revisao cega adicional e ganha selo de destaque.')),
                ('tem_resenha', models.BooleanField(db_index=True, default=False, help_text='Cache para filtros — atualizado automaticamente no save().')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('submetida_em', models.DateTimeField(blank=True, null=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical análise',
                'verbose_name_plural': 'historical análises',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estrutural', 'Revisão estrutural (análise)'), ('cega', 'Revisão cega (resenha crítica)')], db_index=True, default='estrutural', max_length=15)),
                ('parecer', models.CharField(blank=True, choices=[('aprovar', 'Aprovar'), ('ajustes', 'Solicitar ajustes'), ('rejeitar', 'Rejeitar')], max_length=10, null=True)),
                ('comentario_geral', models.TextField(blank=True)),
                ('sorteado_em', models.DateTimeField(auto_now_add=True)),
                ('prazo_em', models.DateTimeField()),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'revisão',
                'verbose_name_plural': 'revisões',
                'ordering': ['-sorteado_em'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField(max_length=600)),
                ('url_wayback', models.URLField(max_length=600)),
                ('capturado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'snapshot de link',
                'verbose_name_plural': 'snapshots de link',
                'ordering': ['-capturado_em'],
            },
        ),
    ]
