# Generated by Django 5.1.15 on 2026-04-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acervo', '0001_initial'),
        ('vocabulario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='analista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analise',
            name='epistemologia',
            field=models.ManyToManyField(blank=True, limit_choices_to={'vocabulario__codigo': 'epistemologia'}, related_name='analises_por_epistemologia', to='vocabulario.termovocabulario'),
        ),
        migrations.AddField(
            model_name='analise',
            name='teoria',
            field=models.ManyToManyField(blank=True, limit_choices_to={'vocabulario__codigo': 'teoria'}, related_name='analises_por_teoria', to='vocabulario.termovocabulario'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='base_consulta',
            field=models.ForeignKey(blank=True, limit_choices_to={'vocabulario__codigo': 'base'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artigos_por_base', to='vocabulario.termovocabulario'),
        ),
        migrations.AddField(
            model_name='analise',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises', to='acervo.artigo'),
        ),
        migrations.AddField(
            model_name='historicalanalise',
            name='analista',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalise',
            name='artigo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acervo.artigo'),
        ),
        migrations.AddField(
            model_name='historicalanalise',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revisao',
            name='analise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='acervo.analise'),
        ),
        migrations.AddField(
            model_name='revisao',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentariorevisao',
            name='revisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='acervo.revisao'),
        ),
        migrations.AddField(
            model_name='snapshotlink',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='acervo.artigo'),
        ),
        migrations.AddConstraint(
            model_name='analise',
            constraint=models.UniqueConstraint(fields=('artigo', 'analista'), name='uniq_analise_por_analista_por_artigo'),
        ),
        migrations.AddConstraint(
            model_name='revisao',
            constraint=models.UniqueConstraint(fields=('analise', 'revisor', 'tipo'), name='uniq_revisao_por_revisor_tipo'),
        ),
    ]
