# Generated by Django 5.1.15 on 2026-05-01 02:43

from django.db import migrations, models


def _move_legacy_doi_para_interno(apps, schema_editor):
    """
    Para artigos do legado importados com `doi='legacy:HASH'`: move o valor
    para `identificador_interno` e zera o campo `doi`. Idempotente —
    rodando duas vezes não duplica.
    """
    Artigo = apps.get_model("acervo", "Artigo")
    qs = Artigo.objects.filter(doi__startswith="legacy:")
    for artigo in qs.iterator(chunk_size=200):
        artigo.identificador_interno = artigo.doi
        artigo.doi = None
        artigo.save(update_fields=["identificador_interno", "doi"])


def _reverte_legacy_para_doi(apps, schema_editor):
    """Reverso: volta `identificador_interno` para `doi` (antes do schema rollback)."""
    Artigo = apps.get_model("acervo", "Artigo")
    qs = Artigo.objects.filter(identificador_interno__startswith="legacy:", doi__isnull=True)
    for artigo in qs.iterator(chunk_size=200):
        artigo.doi = artigo.identificador_interno
        artigo.identificador_interno = None
        artigo.save(update_fields=["doi", "identificador_interno"])


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0003_embedding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkQuebrado',
            fields=[
            ],
            options={
                'verbose_name': 'link quebrado',
                'verbose_name_plural': 'links quebrados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('acervo.artigo',),
        ),
        migrations.AddField(
            model_name='artigo',
            name='identificador_interno',
            field=models.CharField(blank=True, db_index=True, help_text='Fallback determinístico no formato `legacy:<hash16>` quando não há DOI nem ISBN. Gerado automaticamente.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, help_text='ISBN-10 ou ISBN-13 (sem hífens). Usado para livros e capítulos.', max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='tipo_publicacao',
            field=models.CharField(choices=[('artigo', 'Artigo de periódico'), ('capitulo', 'Capítulo de livro'), ('livro', 'Livro'), ('dissertacao', 'Dissertação'), ('tese', 'Tese'), ('outro', 'Outro')], db_index=True, default='artigo', max_length=20),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='doi',
            field=models.CharField(blank=True, db_index=True, help_text='DOI canônico (10.xxxx/yyy). Vazio quando a obra é livro ou não tem DOI.', max_length=200, null=True, unique=True),
        ),
        migrations.RunPython(
            _move_legacy_doi_para_interno,
            reverse_code=_reverte_legacy_para_doi,
        ),
    ]
