# Generated by Django 5.1.15 on 2026-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0004_artigo_sem_doi'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='outra_base_consulta',
            field=models.TextField(blank=True, help_text='Base adicional não modelada no vocabulário (campo da curadoria).'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='titulo_traduzido',
            field=models.TextField(blank=True, help_text='Tradução do título (PT-BR) gerada na curadoria.'),
        ),
    ]
