# Generated by Django 5.1.15 on 2026-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0006_analise_editado_em_analise_editado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='idioma',
            field=models.CharField(blank=True, choices=[('pt', 'Português'), ('en', 'Inglês'), ('es', 'Espanhol'), ('fr', 'Francês'), ('de', 'Alemão'), ('it', 'Italiano'), ('outro', 'Outro')], db_index=True, help_text='Idioma de publicação da obra. Vazio = não informado.', max_length=10),
        ),
    ]
