# Generated by Django 5.1.15 on 2026-06-03 16:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0007_artigo_idioma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analise',
            name='aprovada_por',
            field=models.ForeignKey(blank=True, help_text='Curador que aprovou a publicacao desta analise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analise',
            name='motivo_curadoria',
            field=models.TextField(blank=True, help_text='Justificativa do curador ao pedir ajustes ou rejeitar.'),
        ),
        migrations.AddField(
            model_name='historicalanalise',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalanalise',
            name='aprovada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Curador que aprovou a publicacao desta analise.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalise',
            name='motivo_curadoria',
            field=models.TextField(blank=True, help_text='Justificativa do curador ao pedir ajustes ou rejeitar.'),
        ),
        migrations.AlterField(
            model_name='analise',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida para curadoria'), ('publicada', 'Publicada no acervo'), ('rejeitada', 'Rejeitada pela curadoria'), ('legado', 'Legado pré-validado'), ('despublicada', 'Despublicada'), ('em_revisao', 'Em revisão (legado de fluxo)'), ('aprovada', 'Aprovada (legado de fluxo)')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalanalise',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida para curadoria'), ('publicada', 'Publicada no acervo'), ('rejeitada', 'Rejeitada pela curadoria'), ('legado', 'Legado pré-validado'), ('despublicada', 'Despublicada'), ('em_revisao', 'Em revisão (legado de fluxo)'), ('aprovada', 'Aprovada (legado de fluxo)')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='revisao',
            name='analise',
            field=models.ForeignKey(blank=True, help_text='Legado: revisão estrutural de análise (fluxo descontinuado).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='acervo.analise'),
        ),
        migrations.CreateModel(
            name='HistoricalResenha',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('texto', models.TextField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida para revisão cega'), ('em_revisao', 'Em revisão cega'), ('revisada', 'Revisada — aguardando curadoria'), ('publicada', 'Publicada'), ('rejeitada', 'Rejeitada'), ('legado', 'Legado pré-validado')], db_index=True, default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('submetida_em', models.DateTimeField(blank=True, null=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('editado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analise', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acervo.analise')),
                ('confirmada_por', models.ForeignKey(blank=True, db_constraint=False, help_text='Curador que confirmou a publicacao da resenha revisada.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical resenha crítica',
                'verbose_name_plural': 'historical resenhas críticas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida para revisão cega'), ('em_revisao', 'Em revisão cega'), ('revisada', 'Revisada — aguardando curadoria'), ('publicada', 'Publicada'), ('rejeitada', 'Rejeitada'), ('legado', 'Legado pré-validado')], db_index=True, default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('submetida_em', models.DateTimeField(blank=True, null=True)),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('editado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('analise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resenha', to='acervo.analise')),
                ('confirmada_por', models.ForeignKey(blank=True, help_text='Curador que confirmou a publicacao da resenha revisada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenhas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenhas_editadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resenha crítica',
                'verbose_name_plural': 'resenhas críticas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='revisao',
            name='resenha',
            field=models.ForeignKey(blank=True, help_text='Resenha crítica sob revisão cega por pares.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='acervo.resenha'),
        ),
    ]
