# Generated by Django 5.1.15 on 2026-06-03 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0009_migrar_resenhas_e_limpar_revisao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='revisao',
            name='uniq_revisao_por_revisor_tipo',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='resenha_critica',
        ),
        migrations.RemoveField(
            model_name='analise',
            name='tem_resenha',
        ),
        migrations.RemoveField(
            model_name='historicalanalise',
            name='resenha_critica',
        ),
        migrations.RemoveField(
            model_name='historicalanalise',
            name='tem_resenha',
        ),
        migrations.RemoveField(
            model_name='revisao',
            name='analise',
        ),
        migrations.RemoveField(
            model_name='revisao',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='analise',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida para curadoria'), ('publicada', 'Publicada no acervo'), ('rejeitada', 'Rejeitada pela curadoria'), ('legado', 'Legado pré-validado'), ('despublicada', 'Despublicada')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='comentariorevisao',
            name='campo',
            field=models.CharField(help_text="Campo comentado (na revisão de resenha, normalmente 'texto').", max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalanalise',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('submetida', 'Submetida para curadoria'), ('publicada', 'Publicada no acervo'), ('rejeitada', 'Rejeitada pela curadoria'), ('legado', 'Legado pré-validado'), ('despublicada', 'Despublicada')], db_index=True, default='rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='revisao',
            name='resenha',
            field=models.ForeignKey(help_text='Resenha crítica sob revisão cega por pares.', on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='acervo.resenha'),
        ),
        migrations.AddConstraint(
            model_name='revisao',
            constraint=models.UniqueConstraint(fields=('resenha', 'revisor'), name='uniq_revisao_por_revisor_resenha'),
        ),
    ]
