# Generated by Django 5.1.15 on 2026-06-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0011_analise_despublicada_em_analise_despublicada_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='area',
            field=models.CharField(blank=True, choices=[('Ciências Exatas e da Terra', 'Ciências Exatas e da Terra'), ('Ciências Biológicas', 'Ciências Biológicas'), ('Engenharias', 'Engenharias'), ('Ciências da Saúde', 'Ciências da Saúde'), ('Ciências Agrárias', 'Ciências Agrárias'), ('Ciências Sociais Aplicadas', 'Ciências Sociais Aplicadas'), ('Ciências Humanas', 'Ciências Humanas'), ('Linguística, Letras e Artes', 'Linguística, Letras e Artes'), ('Multidisciplinar', 'Multidisciplinar'), ('Outros', 'Outros')], db_index=True, help_text='Grande área do conhecimento (CNPq/CAPES).', max_length=200),
        ),
    ]
