# Generated by Django 5.1.15 on 2026-06-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0013_mapear_areas_legadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='pago_sem_capes',
            field=models.BooleanField(default=False, help_text='Selo: pago e sem acesso pelo Portal CAPES (evitar incluir).'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='artigo_pago',
            field=models.BooleanField(default=False, help_text='Selo: pago, mas acessível pelo Portal CAPES.'),
        ),
    ]
