# Generated by Django 5.1.15 on 2026-06-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0014_artigo_pago_sem_capes_alter_artigo_artigo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='area_outra',
            field=models.CharField(blank=True, help_text="Área especificada quando a área de conhecimento é 'Outros'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='area',
            field=models.CharField(blank=True, choices=[('Psicologia', 'Psicologia'), ('Educação', 'Educação'), ('Comportamento', 'Comportamento'), ('Trabalho e carreira', 'Trabalho e carreira'), ('Relações humanas e sociais', 'Relações humanas e sociais'), ('Outras Ciências Humanas e Sociais', 'Outras Ciências Humanas e Sociais'), ('Interdisciplinar', 'Interdisciplinar'), ('Língua, Linguística, Discurso', 'Língua, Linguística, Discurso'), ('Gestão e Organização', 'Gestão e Organização'), ('Saúde', 'Saúde'), ('Neurociência', 'Neurociência'), ('Computação', 'Computação'), ('Informação e Comunicação', 'Informação e Comunicação'), ('Educação e Psicologia', 'Educação e Psicologia'), ('Psicologia e Ciências Sociais', 'Psicologia e Ciências Sociais'), ('Violência, Crime, Polícia', 'Violência, Crime, Polícia'), ('Ciências Exatas e da Terra', 'Ciências Exatas e da Terra'), ('Necessidades especiais', 'Necessidades especiais'), ('Música', 'Música'), ('Outros', 'Outros')], db_index=True, help_text='Área de conhecimento da Análise Cognitiva (cf. Fróes).', max_length=200),
        ),
    ]
